spring:
  datasource:
    url: jdbc:mysql://localhost:3306/slay
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379

oauth:
  google:
    info-url: ${GOOGLE_INFO_URL}

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  time:
    access-exp: 10800
    refresh-exp: 2592000
